before_script:
  - npm install -g bower
  - bower install -f
script: npm run test-travis
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

cache:
  directories:
    - node_modules

sudo: false

notifications:
  email:
    on_success: always
